export const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";
export const VIEW_PRODUCT_DETAILS = "VIEW_PRODUCT_DETAILS";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const SUBTRACT_PRODUCT = "SUBTRACT_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
